version: 0.1
phases:
  install:
    commands:
      - sudo apt-get update -y
      - curl -sL https://deb.nodesource.com/setup_9.x | bash -
      - sudo apt-get install -y nodejs
      - sudo apt-get install -y npm
      - npm install -g serverless
  build:
    commands:
      - make
      - serverless deploy --stage dev --region us-east-1 --verbose
      - aws s3 cp site/public/output s3://ryangca/
  post_build:
    commands:
      #- . ./test.sh