version: 0.1
phases:
  install:
    commands:
      - sudo apt-get update -y
      - curl -sL https://deb.nodesource.com/setup_9.x | bash -
      - sudo apt-get install -y nodejs
      - npm install -g serverless
      - go get -u github.com/golang/lint/golint
  pre_build:
    commands:
      - golint -set_exit_status functions/...
  build:
    commands:
      - make
      - go test ./...
  post_build:
    commands:
      - serverless deploy --stage dev --region us-east-1 --verbose
      - aws s3 cp site/public/output s3://ryangca/ --recursive
  artifacts:
    files:
      - bin/*
      - .serverless/*