version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - make
      - serverless deploy
  post_build:
#    commands:
#      - . ./test.sh