# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ryangca

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: go1.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
#  hello:
#    handler: bin/hello
#  world:
#    handler: bin/world

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
# events:
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp

#    Define function environment variables here
#    environment:
#      variable2: value2

resources:
  Resources:
    RyangcaDistribution:
       Type: AWS::CloudFront::Distribution
       DependsOn: RyangcaS3Bucket
       Properties:
         DistributionConfig:
           Origins:
           - DomainName: ryangca.s3.amazonaws.com
             Id: myS3Origin
             S3OriginConfig:
               OriginAccessIdentity: ''
           Enabled: 'true'
           PriceClass: PriceClass_100
           DefaultRootObject: index.html
           DefaultCacheBehavior:
             AllowedMethods:
             - DELETE
             - GET
             - HEAD
             - OPTIONS
             - PATCH
             - POST
             - PUT
             TargetOriginId: myS3Origin
             ForwardedValues:
               QueryString: 'false'
               Cookies:
                 Forward: none
             ViewerProtocolPolicy: allow-all
           ViewerCertificate:
             CloudFrontDefaultCertificate: 'true'
#           ViewerCertificate:
#              AcmCertificateArn: !Ref AcmCertificateArn
#              SslSupportMethod: sni-only
    RyangcaS3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ryangca
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
      DeletionPolicy: Retain
    RyangcaBucketPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        PolicyDocument:
          Id: RyangcaS3BucketPolicy
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource:
                Join:
                  - 'arn:aws:s3:::'
                  - Ref: RyangcaS3Bucket
                  - '/*'
        Bucket:
          Ref: RyangcaS3Bucket