---
Resources:

  RyangcaDistribution:
     Type: AWS::CloudFront::Distribution
     DependsOn: RyangcaS3Bucket
     Properties:
       DistributionConfig:
         Origins:
         - DomainName: ryangca.s3-website-us-east-1.amazonaws.com
           Id: myS3Origin
           CustomOriginConfig:
             OriginProtocolPolicy: http-only
         Enabled: 'true'
         PriceClass: PriceClass_100
         DefaultRootObject: index.html
         Aliases:
          - ryangreen.ca
          - ryang.ca
         ViewerCertificate:
          AcmCertificateArn: ${env:ACM_CERT_ARN}
          SslSupportMethod: sni-only
         CustomErrorResponses:
           - ErrorCode: '404'
             ResponsePagePath: "/404.html"
             ResponseCode: '200'
             ErrorCachingMinTTL: '30'
         DefaultCacheBehavior:
           AllowedMethods:
           - DELETE
           - GET
           - HEAD
           - OPTIONS
           - PATCH
           - POST
           - PUT
           TargetOriginId: myS3Origin
           ForwardedValues:
             QueryString: 'false'
             Cookies:
               Forward: none
           ViewerProtocolPolicy: redirect-to-https